rm earthquake_*
rm population_2010.*
rm upload_raster.std*
rm curl.std*
rm population_2010_earthquake*
rm shakemap_padang_*
rm lembang_scenario_intensity*
rm population_2010_lembang_scenario_intensity_*
rm Earthquake_Grou*
rm Population_2010*
rm Shakemap_Padang_2009*
